"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowRight, FileText, Mail, MessageCircle, Phone } from "lucide-react";
import { CONTACT, PageShell, VisualHero } from "../_components/site-shell";

export default function ContactPage() {
  const [lang, setLang] = useState("th");
  const isTh = lang === "th";
  return <PageShell lang={lang} setLang={setLang}>
    <style>{`.contact-grid{display:grid;grid-template-columns:.9fr 1.1fr;gap:54px}.contact-list{display:grid;gap:14px}.contact-card{display:flex;gap:16px;padding:22px;border:1px solid var(--line);background:white;text-decoration:none}.contact-card svg{flex:0 0 auto;color:var(--green-600)}.contact-card strong{display:block}.contact-card span{color:var(--muted);font-size:14px}.contact-start{padding:38px;background:var(--green-950);color:white}.contact-start h2{margin:0 0 12px;font-size:2rem}.contact-start>p{color:rgba(255,255,255,.68)}.contact-start ol{margin:26px 0;padding-left:20px;color:rgba(255,255,255,.76)}.contact-start li{margin-bottom:12px}@media(max-width:800px){.contact-grid{grid-template-columns:1fr}}`}</style>
    <VisualHero image="/hero/energy-consulting.webp" imagePosition="center 45%" imageAlt={isTh?"ทีมที่ปรึกษาโครงการพลังงาน":"Energy project consulting team"} kicker="Contact" title={isTh?"เริ่มคุยจากข้อมูลที่คุณมี":"Start with the information you have"} lead={isTh?"ไม่ต้องเตรียมทุกอย่างให้ครบ ทีมงานจะช่วยถามต่อเพื่อแยกว่าโครงการควรเดินหน้าอย่างไร":"You do not need every detail ready. Our team will guide the next questions and practical direction."}><div className="visual-hero__actions"><Link href="/quote" className="site-btn site-btn--orange" scroll>{isTh?"กรอกข้อมูลโครงการ":"Share project details"}<ArrowRight size={16}/></Link></div></VisualHero>
    <section className="site-section"><div className="site-container contact-grid"><div><span className="site-kicker">Direct contact</span><h2 className="site-title">{isTh?"ช่องทางติดต่อจริง":"Direct contact channels"}</h2><div className="contact-list" style={{marginTop:30}}><a className="contact-card" href={`tel:${CONTACT.phone}`}><Phone size={23}/><div><strong>{CONTACT.phoneDisplay}</strong><span>{isTh?"โทรศัพท์":"Phone"}</span></div></a><a className="contact-card" href={`mailto:${CONTACT.email}`}><Mail size={23}/><div><strong>{CONTACT.email}</strong><span>Email</span></div></a><a className="contact-card" href={`https://line.me/ti/p/~${CONTACT.line}`} target="_blank" rel="noreferrer"><MessageCircle size={23}/><div><strong>LINE: {CONTACT.line}</strong><span>{isTh?"แชตกับทีมงาน":"Chat with the team"}</span></div></a></div></div><div className="contact-start"><FileText size={28}/><h2>{isTh?"ข้อมูลที่ช่วยให้เริ่มได้เร็วขึ้น":"Information that helps us start faster"}</h2><p>{isTh?"ส่งเท่าที่มีได้ ไม่จำเป็นต้องรู้พื้นที่หลังคาหรือสเปกอุปกรณ์":"Send whatever is available; exact roof area or equipment specifications are not required."}</p><ol><li>{isTh?"บิลค่าไฟล่าสุดหรือค่าไฟเฉลี่ย":"Recent electricity bill or average bill"}</li><li>{isTh?"ประเภทสถานที่และจังหวัด":"Site type and province"}</li><li>{isTh?"ช่วงเวลาที่ใช้ไฟมาก":"When electricity use is highest"}</li><li>{isTh?"เป้าหมาย เช่น ลดค่าไฟ สำรองไฟ หรือขอข้อมูลผลิตภัณฑ์":"Objective: savings, backup, or product information"}</li></ol><Link href="/quote" className="site-btn site-btn--orange">{isTh?"กรอกแบบฟอร์มขอคำปรึกษา":"Open consultation form"}<ArrowRight size={16}/></Link></div></div></section>
  </PageShell>;
}
