"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, Eye, Handshake, Scale, ShieldCheck } from "lucide-react";
import { PageShell } from "../_components/site-shell";

export default function AboutPage() {
  const [lang, setLang] = useState("th");
  const isTh = lang === "th";
  return <PageShell lang={lang} setLang={setLang}>
    <section className="page-hero"><div className="site-container page-hero__grid"><div><span className="site-kicker">About Solar ACM</span><h1>{isTh?"ที่ปรึกษาที่ช่วยทำให้การตัดสินใจเรื่องพลังงานชัดเจนขึ้น":"Consultancy that makes energy decisions clearer"}</h1><p>{isTh?"Solar ACM Systems Corporation ช่วยรวบรวมโจทย์ วางแนวทาง และประสานผู้เชี่ยวชาญสำหรับโครงการโซลาร์ ระบบกักเก็บพลังงาน และผลิตภัณฑ์ที่เกี่ยวข้อง":"Solar ACM Systems Corporation helps frame requirements, shape project direction, and coordinate specialists for solar, storage, and related products."}</p><div className="page-hero__actions"><Link href="/contact" className="site-btn site-btn--orange">{isTh?"ติดต่อเรา":"Contact us"}<ArrowRight size={16}/></Link></div></div><div className="page-hero__media"><img src="/portfolio/project-07.jpg" alt={isTh?"โครงการโซลาร์รูฟท็อป":"Solar rooftop project"}/><div className="page-hero__label"><strong>Solar ACM Systems Corporation</strong><span>{isTh?"พลังงานสะอาดที่เริ่มจากข้อมูลจริง":"Clean energy grounded in real information"}</span></div></div></div></section>
    <section className="site-section"><div className="site-container"><div className="section-head"><div className="section-head__copy"><span className="site-kicker">Our principles</span><h2 className="site-title">{isTh?"หลักที่เราใช้ในการทำงาน":"How we approach the work"}</h2></div></div><div className="grid-3">{[[Eye,isTh?"พูดบทบาทให้ชัด":"Clear roles",isTh?"แยกบทบาทที่ปรึกษา ผู้ประสาน และ EPC ผู้ดำเนินการออกจากกัน":"Consultant, coordinator, and executing EPC roles are kept distinct"],[Scale,isTh?"เปรียบเทียบอย่างมีบริบท":"Contextual comparison",isTh?"ไม่มองเฉพาะราคา แต่ดูขอบเขต อุปกรณ์ เงื่อนไข และผู้รับผิดชอบ":"We consider scope, equipment, terms, and responsibility—not price alone"],[Handshake,isTh?"ประสานงานจนเข้าใจตรงกัน":"Aligned coordination",isTh?"ช่วยให้เจ้าของโครงการและผู้เชี่ยวชาญใช้ข้อมูลชุดเดียวกันในการตัดสินใจ":"We help owners and specialists make decisions from shared information"]].map(([Icon,title,desc])=><article className="flat-card" key={title}><div className="flat-card__icon"><Icon size={22}/></div><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
    <section className="site-section site-section--soft"><div className="site-container split-section"><div className="split-section__media"><img src="/portfolio/project-09.jpg" alt={isTh?"ระบบโซลาร์บนอาคารอุตสาหกรรม":"Industrial rooftop solar system"}/></div><div><span className="site-kicker">What we do</span><h2 className="site-title">{isTh?"จากคำถามแรก ไปจนถึงการประสานส่งมอบ":"From the first question through delivery coordination"}</h2><ul className="check-list">{(isTh?["รับข้อมูลและทำความเข้าใจโจทย์","ช่วยจัดกรอบการประเมินระบบ","ประสานสำรวจและข้อเสนอจากเครือข่าย","ติดตามคำถาม ขอบเขต และข้อมูลโครงการ","ให้ข้อมูล Kolchar และ FIRESAVE ตามเอกสารที่ได้รับ"]:["Understand requirements and available information","Structure the system assessment","Coordinate surveys and network proposals","Track project questions, scope, and information","Provide documented Kolchar and FIRESAVE information"]).map((item)=><li key={item}><Check size={18}/><span>{item}</span></li>)}</ul><div style={{padding:"18px",borderLeft:"4px solid var(--orange)",background:"var(--orange-soft)"}}><strong>{isTh?"สิ่งที่เราไม่กล่าวอ้าง":"What we do not claim"}</strong><p style={{margin:"5px 0 0",color:"#67584f"}}>{isTh?"เราไม่อ้างตัวเลขผลงาน มาตรฐาน สถานะตัวแทน หรือบทบาท EPC หากยังไม่มีเอกสารยืนยัน":"We do not claim project totals, certifications, distributorship, or EPC roles without supporting documentation."}</p></div></div></div></section>
    <section className="cta-band"><div className="site-container cta-band__inner"><div><h2>{isTh?"มีโจทย์พลังงานที่ยังไม่รู้จะเริ่มตรงไหน?":"Not sure where to start with an energy project?"}</h2><p>{isTh?"เล่าโจทย์ให้เราฟัง แล้วค่อยวางขั้นตอนที่เหมาะสม":"Tell us the situation, then we can shape the next practical step."}</p></div><div className="cta-band__actions"><Link href="/contact" className="site-btn site-btn--orange">{isTh?"คุยกับทีมงาน":"Talk to the team"}<ArrowRight size={16}/></Link></div></div></section>
  </PageShell>;
}
