// Product specifications: supplier brochure 19 July 2026 and price list 10 August 2026.
// Test reports in the supplied compilation refer to different products; do not share ratings between models.
export const fireProducts = [
  { id: 'FS-TH', image: '/firesave/capsule.png', group: 'portable', th: ['แคปซูลดับเพลิงชนิดขว้าง', 'ขนาดกะทัดรัด ใช้แรงขว้างให้บรรจุภัณฑ์แตกเพื่อปล่อยสารดับเพลิง เหมาะเป็นอุปกรณ์เสริมสำหรับเพลิงระยะเริ่มต้น', '650 ± 10 มล.', '790 ± 15 กรัม', '5 ปีนับจากวันผลิต'], en: ['Throwable fire-extinguishing capsule', 'A compact supplemental device that releases liquid agent when its container breaks on impact. Intended for early-stage fires.', '650 ± 10 ml', '790 ± 15 g', '5 years from manufacture'] },
  { id: 'FS-S500 PLUS+', image: '/firesave/spray.png', group: 'portable', th: ['สเปรย์ดับเพลิงแบบพกพา', 'รูปแบบฉีดพ่นสำหรับเล็งสารดับเพลิงไปยังต้นเพลิง ขนาดพกพาได้ สำหรับพิจารณาใช้งานในอาคารและยานพาหนะตามคู่มือ', '500 ± 5 มล.', '690 ± 15 กรัม', '3 ปีนับจากวันผลิต'], en: ['Portable fire-extinguishing spray', 'A handheld spray for directing extinguishing agent at an early-stage fire. Consider for buildings and vehicles subject to the product instructions.', '500 ± 5 ml', '690 ± 15 g', '3 years from manufacture'] },
  { id: 'FS-CO', image: '/firesave/cooking.png', group: 'specialist', th: ['ซองดับเพลิงสำหรับน้ำมันทำอาหาร', 'ผลิตภัณฑ์เฉพาะสำหรับน้ำมันประกอบอาหาร เหมาะให้ฝ่ายความปลอดภัยประเมินสำหรับครัวและโรงอาหาร', 'เลือกตามปริมาตรน้ำมันและคู่มือ'], en: ['Cooking-oil fire-extinguishing pack', 'A dedicated cooking-oil product for assessment in kitchens and staff canteens.', 'Select for oil volume and product instructions'] },
  { id: 'SUS-1000', image: '/firesave/sus-1000.png', group: 'cylinder', th: ['ถังดับเพลิงชนิดน้ำยาเหลว · สเตนเลส', 'ถังขนาด 10 ปอนด์ สำหรับพิจารณาจัดซื้อร่วมกับอุปกรณ์พกพา โดยเลือกตามประเภทเพลิงและข้อกำหนดหน้างาน', 'ขอรายละเอียดรุ่นและเงื่อนไขบริการ'], en: ['Liquid-agent extinguisher · stainless steel', 'A 10 lb cylinder option to assess alongside portable equipment, selected for the fire class and site requirements.', 'Request model and service details'] },
  { id: 'FER-1000', image: '/firesave/fer-1000.png', group: 'cylinder', th: ['ถังดับเพลิงชนิดน้ำยาเหลว · ถังเหล็ก', 'ถังเหล็กสีน้ำเงิน ขนาด 10 ปอนด์ พร้อมประสานข้อมูลสินค้าและการดูแลหลังใช้งานตามเงื่อนไขผู้จำหน่าย', 'ขอรายละเอียดรุ่นและเงื่อนไขบริการ'], en: ['Liquid-agent extinguisher · steel', 'A blue 10 lb steel-cylinder option, with product and after-use service information available on request.', 'Request model and service details'] },
  { id: 'FS-CB', image: '/firesave/agent-b.png', group: 'specialist', th: ['หัวเชื้อน้ำยาดับเพลิงประเภท B', 'สำหรับพิจารณาโดยทีมดับเพลิงที่ดูแลความเสี่ยงจากเชื้อเพลิงเหลว ต้องตรวจสูตร อัตราผสม และอุปกรณ์ที่ใช้ร่วมกัน', 'บรรจุ 20 ลิตร ตามรายการสินค้า'], en: ['Class B extinguishing concentrate', 'For fire-response teams assessing liquid-fuel hazards. Confirm formulation, dilution and equipment compatibility.', '20 litre supply format'] },
  { id: 'FS-FT', image: '/firesave/agent-ft.png', group: 'specialist', th: ['หัวเชื้อน้ำยาดับเพลิงทั่วไป / รถดับเพลิง', 'สำหรับทีมดับเพลิงและอุปกรณ์ฉีดพ่นที่เหมาะสม ให้ยืนยันอัตราผสมของสินค้าที่ส่งมอบก่อนใช้งาน', 'บรรจุ 20 ลิตร ตามรายการสินค้า'], en: ['General / fire-truck extinguishing concentrate', 'For fire-response teams and suitable delivery equipment. Confirm the supplied formulation and dilution before use.', '20 litre supply format'] },
  { id: 'FS-WF', image: '/firesave/agent-wf.png', group: 'specialist', th: ['หัวเชื้อน้ำยาสำหรับดับไฟป่า', 'สำหรับหน่วยปฏิบัติการที่ต้องการพิจารณาน้ำยาและระบบฉีดพ่นสำหรับงานไฟป่า', 'บรรจุ 20 ลิตร ตามรายการสินค้า'], en: ['Wildfire extinguishing concentrate', 'For response teams assessing agents and delivery equipment for wildfire operations.', '20 litre supply format'] },
  { id: 'CABINET', image: '/firesave/cabinet.png', group: 'accessory', th: ['ตู้เก็บแคปซูลหรือสเปรย์', 'จัดเก็บอุปกรณ์ให้เป็นจุดและมองเห็นได้ง่าย เลือกจำนวนและตำแหน่งร่วมกับฝ่ายความปลอดภัย', 'ตู้เปล่า · สินค้าภายในแยกเสนอราคา'], en: ['Capsule / spray storage cabinet', 'Organize equipment at visible locations. Agree quantities and placement with the site safety team.', 'Empty cabinet · contents quoted separately'] },
  { id: 'BACKPACK', image: '/firesave/backpack.png', group: 'accessory', th: ['เครื่องฉีดพ่นแบบสะพายหลัง', 'อุปกรณ์เสริมสำหรับเจ้าหน้าที่ปฏิบัติการ ต้องตรวจความเข้ากันได้กับน้ำยาและฝึกใช้งานก่อนนำไปใช้จริง', 'ขนาดบรรจุ 25 ลิตร ตามรายการสินค้า'], en: ['Backpack sprayer', 'Equipment for trained response personnel. Confirm agent compatibility and training requirements.', '25 litre capacity listed by supplier'] },
];

// Model-specific store copy based on the supplier brochure dated 19 July 2026.
// Accessories use the supplied price list. Keep claims scoped to each model.
export const fireShopDetails = {
  'FS-TH': {
    th: { tag:'เพลิงระยะเริ่มต้น · A/B/C', use:['โรงงาน โกดัง สำนักงาน และจุดเสี่ยงที่ต้องหยิบใช้ได้รวดเร็ว','ใช้เป็นอุปกรณ์เสริมสำหรับเข้าถึงต้นเพลิงจากระยะห่างตามคู่มือ'], difference:['ขว้างให้ภาชนะแตกเพื่อกระจายสาร โดยไม่ใช้ถังแรงดัน','น้ำหนักไม่ถึง 1 กก. และผู้ผลิตระบุว่าไม่ต้องบำรุงรักษาตลอดอายุผลิตภัณฑ์'], specs:['สารดับเพลิง 650 ± 10 มล.','น้ำหนัก 790 ± 15 กรัม','อายุ 5 ปี · เก็บ -10 ถึง +60°C'], caution:'ใช้ครั้งเดียว ต้องรักษาทางหนี และห้ามเข้าใกล้เพลิงที่ลุกลามแล้ว' },
    en: { tag:'Early-stage fires · A/B/C', use:['Factories, warehouses, offices and quick-access risk points','A supplemental device for reaching the fire base from the instructed distance'], difference:['Breaks on impact to disperse agent without a pressurized cylinder','Under 1 kg and listed as maintenance-free during product life'], specs:['Agent 650 ± 10 ml','Weight 790 ± 15 g','5-year life · storage -10 to +60°C'], caution:'Single-use. Maintain an escape route and never approach a developed fire.' }
  },
  'FS-S500 PLUS+': {
    th: { tag:'พกพา · A/B/C/K', use:['บ้าน คอนโด สำนักงาน โรงเรียน โรงพยาบาล และยานพาหนะ','ผู้ใช้ที่ต้องการเล็งและควบคุมทิศทางการฉีดกับเพลิงระยะเริ่มต้น'], difference:['ทรงสเปรย์จับถนัดมือ เล็งสารไปยังต้นเพลิงได้โดยตรง','รองรับประเภทเพลิงตามที่ระบุได้กว้างในรูปแบบพกพา'], specs:['สาร 500 ± 5 มล. · น้ำหนัก 690 ± 15 กรัม','แรงดัน 8–10 บาร์','อายุ 3 ปี · เก็บ 0 ถึง +65°C'], caution:'เขย่า ปลดสลัก และฉีดตามคู่มือ ใช้เมื่อยังมีทางหนีที่ปลอดภัยเท่านั้น' },
    en: { tag:'Portable · A/B/C/K', use:['Homes, condominiums, offices, schools, hospitals and vehicles','Users needing directed spray control on an early-stage fire'], difference:['Handheld format for aiming at the fire base','A broad listed fire-class range in a portable format'], specs:['Agent 500 ± 5 ml · weight 690 ± 15 g','Pressure 8–10 bar','3-year life · storage 0 to +65°C'], caution:'Shake, unlock and spray as instructed. Use only with a safe escape route.' }
  },
  'FS-CO': {
    th: { tag:'ครัว · เพลิงน้ำมัน K', use:['ครัวบ้าน ร้านอาหาร โรงอาหาร และพื้นที่ทอดอาหาร','น้ำมันพืชหรือสัตว์ปริมาตรไม่เกิน 1 ลิตรต่อซองตามผู้ผลิต'], difference:['ออกแบบเฉพาะสำหรับเพลิงน้ำมันประกอบอาหาร ซึ่งห้ามใช้น้ำดับ','ขนาดเล็ก จัดเก็บใกล้ครัวในจุดที่เข้าถึงได้อย่างปลอดภัย'], specs:['สาร 80 ± 5 มล. · น้ำหนัก 110 ± 15 กรัม','อายุ 2 ปี','เก็บ -5 ถึง +60°C'], caution:'ปิดแหล่งความร้อนเมื่อทำได้อย่างปลอดภัย ใช้ตามปริมาตรที่กำหนด และห้ามใช้น้ำ' },
    en: { tag:'Kitchen · Class K', use:['Home kitchens, restaurants, canteens and frying stations','Vegetable/animal cooking oil up to 1 litre per pack as listed'], difference:['Dedicated to cooking-oil fires, where water must never be used','Compact storage near a safely accessible kitchen point'], specs:['Agent 80 ± 5 ml · weight 110 ± 15 g','2-year life','Storage -5 to +60°C'], caution:'Turn off heat if safe, observe the stated oil volume and never apply water.' }
  },
  'SUS-1000': {
    th: { tag:'ถังน้ำยาเหลว · สเตนเลส', use:['อาคาร โรงงาน และจุดติดตั้งตามแผนความปลอดภัย','โครงการที่ต้องการตัวถังสเตนเลสและเลือกประเภทเพลิงให้ตรงหน้างาน'], difference:['ถัง 10 ปอนด์สำหรับรวมในแผนป้องกันอัคคีภัย','สเตนเลสเป็นทางเลือกด้านวัสดุและภาพลักษณ์จุดติดตั้ง'], specs:['ขนาด 10 ปอนด์','สารดับเพลิงแบบน้ำยาเหลว','ยืนยันพิกัดดับเพลิงและรอบตรวจตามรุ่นที่ส่งมอบ'], caution:'ให้ จป. หรือผู้เชี่ยวชาญตรวจตำแหน่ง จำนวน และประเภทเพลิงก่อนสั่งซื้อ' },
    en: { tag:'Liquid agent · stainless', use:['Buildings, factories and planned safety points','Projects preferring stainless after matching the unit to site fire classes'], difference:['10 lb cylinder format for a site fire plan','Stainless construction as a material and visual option'], specs:['Listed size 10 lb','Liquid-agent format','Confirm ratings and inspection terms for the delivered model'], caution:'Have a safety specialist confirm placement, quantity and fire class before purchase.' }
  },
  'FER-1000': {
    th: { tag:'ถังน้ำยาเหลว · เหล็ก', use:['อาคาร โรงงาน โกดัง และจุดติดตั้งถังตามแผน','งานที่ต้องการถังเหล็ก 10 ปอนด์หลายจุด'], difference:['ถังเหล็กเป็นทางเลือกสำหรับการจัดวางหลายตำแหน่ง','ใช้น้ำยาเหลวแทนรูปแบบผง โดยต้องเลือกให้ตรงประเภทเพลิง'], specs:['ขนาด 10 ปอนด์','ตัวถังเหล็กสีน้ำเงิน','ยืนยันพิกัดดับเพลิงและรอบตรวจตามรุ่นที่ส่งมอบ'], caution:'ไม่ควรเลือกจากราคาเพียงอย่างเดียว ต้องตรวจข้อกำหนดหน้างานก่อน' },
    en: { tag:'Liquid agent · steel', use:['Buildings, factories, warehouses and planned extinguisher points','Sites needing multiple 10 lb steel cylinders'], difference:['A steel option for deployment across multiple points','Liquid-agent rather than dry-powder format, subject to fire-class matching'], specs:['Listed size 10 lb','Blue steel cylinder','Confirm ratings and inspection terms for the delivered model'], caution:'Do not select on price alone; confirm site requirements first.' }
  },
  'FS-CB': {
    th: { tag:'หัวเชื้อ · ของเหลวไวไฟ B', use:['คลังเชื้อเพลิง โรงงาน และทีมที่ดูแลของเหลวไวไฟ','ระบบฉีดพ่นหรืออุปกรณ์ผสมที่ตรวจความเข้ากันได้แล้ว'], difference:['สูตรเพลิง B ช่วยสร้างชั้นฟิล์ม/โฟมปกคลุมผิวเชื้อเพลิง','เป็นหัวเชื้อสำหรับทีมปฏิบัติการ ไม่ใช่อุปกรณ์พร้อมฉีดทั่วไป'], specs:['จำหน่ายขนาด 20 ลิตร','ต้องผสมน้ำตามสเปกล็อตสินค้า','ตรวจอุปกรณ์จ่ายสารก่อนใช้'], caution:'สำหรับผู้ผ่านการฝึก ต้องยืนยันอัตราผสม อุปกรณ์ และเชื้อเพลิงก่อนใช้งาน' },
    en: { tag:'Concentrate · Class B liquids', use:['Fuel storage, factories and flammable-liquid response teams','Verified compatible proportioning and delivery systems'], difference:['Class-B formulation intended to form a film/foam layer over fuel','An operational concentrate—not a ready-to-spray consumer unit'], specs:['Sold in 20 litres','Dilute to delivered-batch specification','Verify delivery equipment before use'], caution:'For trained personnel. Confirm dilution, equipment and fuel compatibility.' }
  },
  'FS-FT': {
    th: { tag:'หัวเชื้อ · รถดับเพลิง', use:['เทศบาล โรงงาน หน่วยกู้ภัย และทีมที่มีรถดับเพลิง','งานเพลิงประเภท A ตามเอกสารผลิตภัณฑ์'], difference:['หัวเชื้อผสมน้ำสำหรับระบบฉีดพ่นที่เหมาะสม','รองรับการเตรียมสารปริมาณมากจากหัวเชื้อ 20 ลิตร'], specs:['จำหน่ายขนาด 20 ลิตร','ต้องตรวจสูตรและอัตราผสมจากล็อตที่ส่งมอบ','ใช้อุปกรณ์จ่ายสารที่รองรับ'], caution:'เอกสารที่ได้รับมีอัตราผสมต่างเวอร์ชัน จึงต้องยืนยันสเปกล็อตก่อนใช้ทุกครั้ง' },
    en: { tag:'Concentrate · fire appliance', use:['Municipal, factory and rescue teams with fire appliances','Class A operations described in product documents'], difference:['Water-mix concentrate for compatible delivery systems','Supports larger operational volumes from a 20 litre concentrate'], specs:['Sold in 20 litres','Verify delivered formulation and dilution','Requires compatible equipment'], caution:'Documents contain different ratio versions; always confirm the delivered batch specification.' }
  },
  'FS-WF': {
    th: { tag:'หัวเชื้อ · งานไฟป่า', use:['หน่วยป้องกันไฟป่า ท้องถิ่น และทีมภาคสนาม','ระบบฉีดพ่นที่เหมาะสมภายใต้แผนปฏิบัติการ'], difference:['สูตรเฉพาะสำหรับงานไฟป่าและการควบคุมการลุกลามตามผู้ผลิต','หัวเชื้อ 20 ลิตรรองรับการเตรียมน้ำยาภาคสนาม'], specs:['จำหน่ายขนาด 20 ลิตร','ผสมน้ำตามสเปกล็อตที่ส่งมอบ','ตรวจความเข้ากันได้กับเครื่องฉีดพ่น'], caution:'สำหรับเจ้าหน้าที่ที่ผ่านการฝึกและต้องอยู่ภายใต้แผนความปลอดภัยของหน่วยงาน' },
    en: { tag:'Concentrate · wildfire', use:['Wildfire units, local authorities and field-response teams','Compatible delivery systems under an incident plan'], difference:['Formulated for wildfire control and spread reduction according to supplier information','20 litre concentrate supports field preparation'], specs:['Sold in 20 litres','Dilute to delivered-batch specification','Confirm sprayer compatibility'], caution:'For trained responders under the responsible agency’s safety plan.' }
  },
  CABINET: {
    th: { tag:'จัดเก็บ · จุดพร้อมใช้', use:['สำนักงาน โรงงาน ร้านค้า และจุดที่ต้องเห็นอุปกรณ์ชัดเจน','จัดวางแคปซูลหรือสเปรย์ตามแผนฝ่ายความปลอดภัย'], difference:['ระบุตำแหน่งอุปกรณ์ให้ค้นหาได้เร็ว','ลดโอกาสอุปกรณ์ถูกวางผิดที่หรือมีสิ่งของบัง'], specs:['เป็นตู้เปล่า','สินค้าในตู้จำหน่ายแยก','ออกแบบจำนวนและตำแหน่งตามพื้นที่'], caution:'ตู้ไม่ใช่อุปกรณ์ดับเพลิง และต้องไม่ติดตั้งกีดขวางทางหนี' },
    en: { tag:'Storage · visible point', use:['Offices, factories and retail sites needing visible equipment','Planned capsule or spray points'], difference:['Makes equipment locations quicker to identify','Helps prevent portable equipment being misplaced or obscured'], specs:['Empty cabinet','Contents sold separately','Plan quantity and placement for the site'], caution:'The cabinet does not extinguish fire and must not obstruct an escape route.' }
  },
  BACKPACK: {
    th: { tag:'เครื่องฉีดพ่น · เจ้าหน้าที่', use:['ทีมดับเพลิงภาคสนาม หน่วยกู้ภัย และพื้นที่รถเข้าถึงยาก','ใช้ร่วมกับสารที่ยืนยันว่าเข้ากันได้กับเครื่อง'], difference:['รูปแบบสะพายหลังช่วยให้เจ้าหน้าที่เคลื่อนที่พร้อมระบบฉีดพ่น','ความจุ 25 ลิตรเป็นอุปกรณ์งานปฏิบัติการ'], specs:['ความจุ 25 ลิตร','ไม่รวมการรับรองว่าน้ำยาทุกสูตรใช้ร่วมกันได้','ตรวจหัวฉีด ซีล และระบบก่อนใช้'], caution:'ต้องฝึกใช้งาน สวม PPE และห้ามเติมสารที่ยังไม่ยืนยันความเข้ากันได้' },
    en: { tag:'Delivery equipment · crew', use:['Field fire teams, rescue units and vehicle-inaccessible areas','Agents confirmed as compatible with the equipment'], difference:['Backpack format allows trained personnel to move with the system','25 litre capacity is operational equipment'], specs:['Listed capacity 25 litres','Compatibility with every agent is not implied','Inspect nozzle, seals and system'], caution:'Training and PPE are required. Confirm agent compatibility before filling.' }
  }
};

export const fireComparison = {
  th: [
    ['การปล่อยสาร', 'ขว้างให้แตก · ไม่มีถังแรงดัน', 'เล็งและฉีดพ่น · มีแรงดันภายใน', 'ฉีดผ่านหัวฉีด/สาย ตามประเภทถัง'],
    ['ขนาดและน้ำหนัก', '650 มล. · ประมาณ 790 กรัม', '500 มล. · ประมาณ 690 กรัม', 'มีหลายขนาด ต้องเทียบรุ่นที่ต้องการ'],
    ['สิ่งที่ผู้ใช้ต้องฝึก', 'เลือกจุดกระแทกและรักษาทางหนี', 'ปลดล็อค เล็ง และควบคุมการฉีด', 'ปลดสลัก เล็ง กด และกวาดตามคู่มือ'],
    ['การตรวจดูแล', 'ตรวจสภาพ รอยรั่ว และวันหมดอายุ', 'ตรวจสภาพ วันหมดอายุ และคู่มือ', 'ตรวจตามประเภทถังและแผนของสถานที่'],
    ['บทบาทในการจัดซื้อ', 'อุปกรณ์เสริมแบบพกพา ใช้ครั้งเดียว', 'อุปกรณ์เสริมแบบฉีดพ่น', 'อุปกรณ์ตามแผนป้องกันอัคคีภัยของสถานที่'],
  ],
  en: [
    ['Agent delivery', 'Breaks on impact · no pressurized cylinder', 'Directed spray · internally pressurized', 'Nozzle/hose delivery depending on type'],
    ['Size & weight', '650 ml · approximately 790 g', '500 ml · approximately 690 g', 'Varies by model and capacity'],
    ['Training focus', 'Impact placement and a clear escape route', 'Unlocking, aiming and spray control', 'Pin, aim, squeeze and sweep per instructions'],
    ['Routine checks', 'Condition, leaks and expiry date', 'Condition, expiry and instructions', 'Type-specific inspection and site schedule'],
    ['Procurement role', 'Single-use supplemental portable device', 'Supplemental directed-spray device', 'Equipment selected for the site fire plan'],
  ],
};
